In [1]:
import numpy as np

In [2]:
SA = np.array([['Student_1', 59, 64, 94, 87, 81],

                          ['Student_2', 8, 56, 18, 58, 69],

                          ['Student_3', 7, 20, 60, 63, 42],

                          ['Student_4', 71, 94, 71, 68, 13],

                          ['Student_5', 89, 1, 16, 33, 40],

                          ['Student_6', 4, 25, 48, 41, 84],

                          ['Student_7', 3, 79, 46, 9, 71],

                          ['Student_8', 87, 77, 75, 15, 69],

                          ['Student_9', 61, 1, 48, 98, 23],

                          ['Student_10', 98, 60, 24, 66, 56],

                          ['Student_11', 58, 12, 75, 7, 98],

                          ['Student_12', 23, 62, 6, 35, 37],

                          ['Student_13', 14, 25, 87, 56, 8],

                          ['Student_14', 68, 1, 81, 11, 61],

                          ['Student_15', 11, 69, 35, 17, 66]], dtype=object)

In [3]:
suba=SA[ :,1]
subb=SA[:,2]
print("mark of sub a :",suba)
print("mark of sub b :",subb)

mark of sub a : [59 8 7 71 89 4 3 87 61 98 58 23 14 68 11]
mark of sub b : [64 56 20 94 1 25 79 77 1 60 12 62 25 1 69]


In [4]:
suba>subb

array([False, False, False, False,  True, False, False,  True,  True,
        True,  True, False, False,  True, False])

In [5]:
len(SA[suba>subb])

6

In [6]:
SA


array([['Student_1', 59, 64, 94, 87, 81],
       ['Student_2', 8, 56, 18, 58, 69],
       ['Student_3', 7, 20, 60, 63, 42],
       ['Student_4', 71, 94, 71, 68, 13],
       ['Student_5', 89, 1, 16, 33, 40],
       ['Student_6', 4, 25, 48, 41, 84],
       ['Student_7', 3, 79, 46, 9, 71],
       ['Student_8', 87, 77, 75, 15, 69],
       ['Student_9', 61, 1, 48, 98, 23],
       ['Student_10', 98, 60, 24, 66, 56],
       ['Student_11', 58, 12, 75, 7, 98],
       ['Student_12', 23, 62, 6, 35, 37],
       ['Student_13', 14, 25, 87, 56, 8],
       ['Student_14', 68, 1, 81, 11, 61],
       ['Student_15', 11, 69, 35, 17, 66]], dtype=object)

In [7]:
a=SA[:,1]
a.mean()


44.06666666666667

In [8]:
p=SA[:,1]
p

array([59, 8, 7, 71, 89, 4, 3, 87, 61, 98, 58, 23, 14, 68, 11],
      dtype=object)

In [9]:
sum(p)
avg1=sum(p)/len(p)

In [10]:

avg1

44.06666666666667

In [11]:
SA

array([['Student_1', 59, 64, 94, 87, 81],
       ['Student_2', 8, 56, 18, 58, 69],
       ['Student_3', 7, 20, 60, 63, 42],
       ['Student_4', 71, 94, 71, 68, 13],
       ['Student_5', 89, 1, 16, 33, 40],
       ['Student_6', 4, 25, 48, 41, 84],
       ['Student_7', 3, 79, 46, 9, 71],
       ['Student_8', 87, 77, 75, 15, 69],
       ['Student_9', 61, 1, 48, 98, 23],
       ['Student_10', 98, 60, 24, 66, 56],
       ['Student_11', 58, 12, 75, 7, 98],
       ['Student_12', 23, 62, 6, 35, 37],
       ['Student_13', 14, 25, 87, 56, 8],
       ['Student_14', 68, 1, 81, 11, 61],
       ['Student_15', 11, 69, 35, 17, 66]], dtype=object)

In [12]:
SA[14]#15 ka data

array(['Student_15', 11, 69, 35, 17, 66], dtype=object)

In [13]:
s15a=SA[14][1]
print("s15a: ",s15a)

s15a:  11


In [14]:
s15b=SA[14][2]
print("s15b: ",s15b)

s15b:  69


In [15]:
cond=(suba > s15a)&(subb > s15b)
cond
#len(SA[cond])

array([False, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False])

In [16]:
len(SA)

15

In [17]:
SA

array([['Student_1', 59, 64, 94, 87, 81],
       ['Student_2', 8, 56, 18, 58, 69],
       ['Student_3', 7, 20, 60, 63, 42],
       ['Student_4', 71, 94, 71, 68, 13],
       ['Student_5', 89, 1, 16, 33, 40],
       ['Student_6', 4, 25, 48, 41, 84],
       ['Student_7', 3, 79, 46, 9, 71],
       ['Student_8', 87, 77, 75, 15, 69],
       ['Student_9', 61, 1, 48, 98, 23],
       ['Student_10', 98, 60, 24, 66, 56],
       ['Student_11', 58, 12, 75, 7, 98],
       ['Student_12', 23, 62, 6, 35, 37],
       ['Student_13', 14, 25, 87, 56, 8],
       ['Student_14', 68, 1, 81, 11, 61],
       ['Student_15', 11, 69, 35, 17, 66]], dtype=object)

In [18]:
mark=SA[3:10 ,:]
mark

array([['Student_4', 71, 94, 71, 68, 13],
       ['Student_5', 89, 1, 16, 33, 40],
       ['Student_6', 4, 25, 48, 41, 84],
       ['Student_7', 3, 79, 46, 9, 71],
       ['Student_8', 87, 77, 75, 15, 69],
       ['Student_9', 61, 1, 48, 98, 23],
       ['Student_10', 98, 60, 24, 66, 56]], dtype=object)

In [19]:
v=(mark[: ,1:])
v

array([[71, 94, 71, 68, 13],
       [89, 1, 16, 33, 40],
       [4, 25, 48, 41, 84],
       [3, 79, 46, 9, 71],
       [87, 77, 75, 15, 69],
       [61, 1, 48, 98, 23],
       [98, 60, 24, 66, 56]], dtype=object)

In [20]:
TM = v.sum(axis=1)
TM


array([317, 179, 202, 208, 323, 231, 304], dtype=object)

In [21]:
np.mean(TM)

252.0

In [22]:
a=np.array(["a","b","b",'c',"a"])
u=np.unique(a,return_index=True)
u
u=np.unique(a,return_inverse=True)
u

(array(['a', 'b', 'c'], dtype='<U1'), array([0, 1, 1, 2, 0]))

In [23]:
from ctypes import c_int16
#broadcasting in nuumpy array
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

c1=a*b
c1

array([ 10,  40,  90, 160])

In [24]:
np.arange(3)

array([0, 1, 2])

In [25]:
np.arange(3)+5

array([5, 6, 7])

In [26]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [27]:
import numpy as np

In [28]:
BA = np.array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular','oct'],

       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular','may'],

       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular','apr'],

       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown','jun'],

       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown','may'],

       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular','feb'],

       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular','may'],

       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular','may'],

       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular','apr'],

       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'admin.', 'married', 264.0, 'yes', 'no', 'cellular', 'apr'],

       [36.0, 'technician', 'married', 1109.0, 'no', 'no', 'cellular','aug'],

       [20.0, 'student', 'single', 502.0, 'no', 'no', 'cellular', 'apr'],

       [31.0, 'blue-collar', 'married', 360.0, 'yes', 'yes', 'cellular','jan'],

       [40.0, 'management', 'married', 194.0, 'no', 'yes', 'cellular','aug'],

       [56.0, 'technician', 'married', 4073.0, 'no', 'no', 'cellular','aug'],

       [37.0, 'admin.', 'single', 2317.0, 'yes', 'no', 'cellular', 'apr'],

       [25.0, 'blue-collar', 'single', -221.0, 'yes', 'no', 'unknown','may'],

       [31.0, 'services', 'married', 132.0, 'no', 'no', 'cellular','jul']], dtype=object)

In [29]:
#What is the total bank balance of the first 5 records from the data?


In [30]:
R=BA[:5]
R

array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular',
        'oct'],
       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular',
        'may'],
       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular',
        'apr'],
       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown',
        'jun'],
       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown',
        'may']], dtype=object)

In [31]:
sum(R[ : ,3])

9402.0

In [32]:
#What is the average bank balance?

In [33]:
A=BA[:,3]
A

array([1787.0, 4789.0, 1350.0, 1476.0, 0.0, 747.0, 307.0, 147.0, 221.0,
       -88.0, 9374.0, 264.0, 1109.0, 502.0, 360.0, 194.0, 4073.0, 2317.0,
       -221.0, 132.0], dtype=object)

In [34]:
avg=sum(A)/len(A)
avg

1442.0

In [35]:
#Count the number of people who has a housing?

In [36]:
H=BA[ :, 4]
H

array(['no', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no'],
      dtype=object)

In [37]:
yescount=np.count_nonzero(H=='yes')
yescount

13

In [38]:
#Count the number of people who has a loan?

In [39]:
BA

array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular',
        'oct'],
       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular',
        'may'],
       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular',
        'apr'],
       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown',
        'jun'],
       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown',
        'may'],
       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular',
        'feb'],
       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular',
        'may'],
       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular',
        'may'],
       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown',
        'may'],
       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular',
        'apr'],
       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown',
        'may'],
       [43.0, 'admin.', 'married', 264.0, 'ye

In [40]:
L=BA[ : ,5]
L

array(['no', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no'],
      dtype=object)

In [41]:
yesloan=np.count_nonzero(L=='yes')
yesloan

5

In [42]:
#No of people who have a "cellular" contact and also "married" and hold a "management" job?

In [43]:
BA

array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular',
        'oct'],
       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular',
        'may'],
       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular',
        'apr'],
       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown',
        'jun'],
       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown',
        'may'],
       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular',
        'feb'],
       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular',
        'may'],
       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular',
        'may'],
       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown',
        'may'],
       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular',
        'apr'],
       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown',
        'may'],
       [43.0, 'admin.', 'married', 264.0, 'ye

In [44]:
C=BA[ : ,(1,2,6)]
C

array([['unemployed', 'married', 'cellular'],
       ['services', 'married', 'cellular'],
       ['management', 'single', 'cellular'],
       ['management', 'married', 'unknown'],
       ['blue-collar', 'married', 'unknown'],
       ['management', 'single', 'cellular'],
       ['self-employed', 'married', 'cellular'],
       ['technician', 'married', 'cellular'],
       ['entrepreneur', 'married', 'unknown'],
       ['services', 'married', 'cellular'],
       ['services', 'married', 'unknown'],
       ['admin.', 'married', 'cellular'],
       ['technician', 'married', 'cellular'],
       ['student', 'single', 'cellular'],
       ['blue-collar', 'married', 'cellular'],
       ['management', 'married', 'cellular'],
       ['technician', 'married', 'cellular'],
       ['admin.', 'single', 'cellular'],
       ['blue-collar', 'single', 'unknown'],
       ['services', 'married', 'cellular']], dtype=object)

In [45]:
marital_status=C[: ,1]
marital_status


array(['married', 'married', 'single', 'married', 'married', 'single',
       'married', 'married', 'married', 'married', 'married', 'married',
       'married', 'single', 'married', 'married', 'married', 'single',
       'single', 'married'], dtype=object)

In [46]:
job_type =C[ : ,0]
job_type


array(['unemployed', 'services', 'management', 'management',
       'blue-collar', 'management', 'self-employed', 'technician',
       'entrepreneur', 'services', 'services', 'admin.', 'technician',
       'student', 'blue-collar', 'management', 'technician', 'admin.',
       'blue-collar', 'services'], dtype=object)

In [47]:
contact_type =C[ :,2]
contact_type

array(['cellular', 'cellular', 'cellular', 'unknown', 'unknown',
       'cellular', 'cellular', 'cellular', 'unknown', 'cellular',
       'unknown', 'cellular', 'cellular', 'cellular', 'cellular',
       'cellular', 'cellular', 'cellular', 'unknown', 'cellular'],
      dtype=object)

In [48]:
#No of people who have a "cellular" contact and also "married" and hold a "management" j

filtered_data = (contact_type == 'cellular') & (marital_status == 'married') & (job_type == 'management')
filtered_data
d=filtered_data
d

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False])

In [49]:
dat=np.count_nonzero(d)
dat

1

In [50]:
#Find the total balance of the customers aged between 25 and 40(both inclusive).


In [51]:
ages=BA[ :,0]
filtered_data = (ages >= 25) & (ages <= 40)
filtered_data

array([ True,  True,  True,  True, False,  True,  True,  True, False,
       False,  True, False,  True, False,  True,  True, False,  True,
        True,  True])

In [52]:
total_balance=BA[:,3]
total_balance

array([1787.0, 4789.0, 1350.0, 1476.0, 0.0, 747.0, 307.0, 147.0, 221.0,
       -88.0, 9374.0, 264.0, 1109.0, 502.0, 360.0, 194.0, 4073.0, 2317.0,
       -221.0, 132.0], dtype=object)

In [53]:
total=np.sum(total_balance[filtered_data])
total

23868.0

In [54]:
#No of people who are single but have more than average bank balance?


In [55]:
import numpy as np

In [56]:
BA

array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular',
        'oct'],
       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular',
        'may'],
       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular',
        'apr'],
       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown',
        'jun'],
       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown',
        'may'],
       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular',
        'feb'],
       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular',
        'may'],
       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular',
        'may'],
       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown',
        'may'],
       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular',
        'apr'],
       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown',
        'may'],
       [43.0, 'admin.', 'married', 264.0, 'ye

In [75]:
maratial_status=BA[ :,2]
m=maratial_status =="single"
m

array([False, False,  True, False, False,  True, False, False, False,
       False, False, False, False,  True, False, False, False,  True,
        True, False])

In [76]:
#No of people who are single but have more than average bank balance?


In [77]:
balance=BA[0:,3]
balance

array([1787.0, 4789.0, 1350.0, 1476.0, 0.0, 747.0, 307.0, 147.0, 221.0,
       -88.0, 9374.0, 264.0, 1109.0, 502.0, 360.0, 194.0, 4073.0, 2317.0,
       -221.0, 132.0], dtype=object)

In [78]:
avg=sum(balance)/len(balance)
avg

1442.0

In [79]:
cond=balance>avg
cond

array([ True,  True, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True,  True,
       False, False])

In [83]:
filter= m&cond
filter

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False])

In [85]:
np.count_nonzero(filter)

1

In [86]:
#No of people who had a loan and housing?

In [88]:
loan=BA[ :,5]
loan

array(['no', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no'],
      dtype=object)

In [89]:
housing=BA[ :,4]
housing

array(['no', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no'],
      dtype=object)

In [95]:

F=(loan=='yes') & (housing=='yes')
F

array([False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False, False])

In [97]:
np.count_nonzero(F)

4

In [98]:
'''Company has decided to give a bonus of 5% of their account balance to those
account holders whose age is more than or equal to 55 years and whose account
 balance is more than 2000. Calculate the sum of the total bank balance
 to the account holders(mentioned above) after crediting their bonus amount.'''

'Company has decided to give a bonus of 5% of their account balance to those \naccount holders whose age is more than or equal to 55 years and whose account\n balance is more than 2000. Calculate the sum of the total bank balance\n to the account holders(mentioned above) after crediting their bonus amount.'

In [111]:
balance=BA[ :,3]
balance

array([1787.0, 4789.0, 1350.0, 1476.0, 0.0, 747.0, 307.0, 147.0, 221.0,
       -88.0, 9374.0, 264.0, 1109.0, 502.0, 360.0, 194.0, 4073.0, 2317.0,
       -221.0, 132.0], dtype=object)

In [121]:
age=BA[ :,0]
age


array([30.0, 33.0, 35.0, 30.0, 59.0, 35.0, 36.0, 39.0, 41.0, 43.0, 39.0,
       43.0, 36.0, 20.0, 31.0, 40.0, 56.0, 37.0, 25.0, 31.0], dtype=object)

In [123]:
filter_data= (age >= 55) & (balance > 2000)
filter_data

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False])

In [125]:
total_balance_with_bonus = np.sum(balance[filter_data] * 1.05)
total_balance_with_bonus

4276.650000000001

In [126]:
x1=np.array([1,2,3,4,5])
x2=np.array([5,4,3])
x1_new = x1[:, np.newaxis]
print(x1 + x2)

ValueError: ignored